### ISSUE TITLE
Api produces duplicate message lines in json resulting in error

### ISSUE THREAD

**Issue by iamgrimm** [remg427/TA-thehive-ce#12]
The Splunk fields "index" and "splunk_server" both produce the same message line in the json resulting in the following error message:
`400/{"type":"CreateError","message":"Observable already exists"}`
When I manually remove the two artifacts with duplicate message lines and manually pull the rest of the incident in it all in without any error.  The duplicated message lines do not match the Splunk fields like the rest of the message files lines do, instead they both say:
`            "message": " - field: _si",`

**Comment by iamgrimm** [comment]
Some additional info, I reformatted my search query in Splunk to eliminate all field except what I needed for my alert, however Splunk has some required fields which you cannot filter out, and these fields are where the error occur.

**Comment by iamgrimm** [comment]
Further information:  appears to occur randomly, not every time.  This is more troubling than every time because I don't know if I have missed an alert.

**Comment by remg427** [comment]
Hi, What version of the TA do you use?

-- 
Sent with K-9 Mail.

**Comment by iamgrimm** [comment]
> Hi, What version of the TA do you use?
> […](#)
> -- Sent with K-9 Mail.

We are using 1.03, it was my understanding that 1.1.1 was still being certified by Splunk for use in Splunk Cloud. Is the app ready for use in the cloud?

**Comment by ntcong** [comment]
I'm using 1.1.1 and can confirm that alerts creating have the bug "Observable already exists"

**Comment by remg427** [comment]
Hi correct 1.1.1 is not certified yet working on 1.1.2 to fix thst

Le 13 octobre 2020 20:06:59 GMT+02:00, iamgrimm <notifications@github.com> a écrit :
>> Hi, What version of the TA do you use?>
>> […](#)>
>> -- Sent with K-9 Mail.>
>>
>We are using 1.03, it was my understanding that 1.1.1 was still being
>certified by Splunk for use in Splunk Cloud. Is the app ready for use
>in the cloud?>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/remg427/TA-thehive-ce/issues/12#issuecomment-707916294

-- 
Sent with K-9 Mail.

**Comment by iamgrimm** [comment]
> Hi correct 1.1.1 is not certified yet working on 1.1.2 to fix thst Le 13 octobre 2020 20:06:59 GMT+02:00, iamgrimm <notifications@github.com> a écrit :
> […](#)
> > Hi, What version of the TA do you use?> > […](#)> > -- Sent with K-9 Mail.> > We are using 1.03, it was my understanding that 1.1.1 was still being certified by Splunk for use in Splunk Cloud. Is the app ready for use in the cloud?> > -- > You are receiving this because you commented.> Reply to this email directly or view it on GitHub:> [#12 (comment)](https://github.com/remg427/TA-thehive-ce/issues/12#issuecomment-707916294)
> -- Sent with K-9 Mail.

I am not sure if this would be a related issue, but splunk provides certain fields in an alert by default (time, index, etc.) and when importing into theHive it breaks those single values into segments all as "other" data types, cluttering up the alert.  Is this related or would it be a separate issue?

**Comment by remg427** [comment]
Hi,
Splunk passes additional fields __mv_* but this cleaned up.
the issue here I think is related to Thehive that does not allow to create 2 alerts with same sourceRef value. 
If in alert action you set for unique a string or a field name that returns the same value the first alert is created the second is not
you can leave that field blank so alert will be created with a generated value 'SPK' + str(int(time.time())) so unique unless you have 2 alerts in the same second

**Comment by iamgrimm** [comment]
I have tried to minimize the fields but it isn't working.  Is there a way you can think of that would eliminate all the extra "other" fields?  I thought this query would send only the requested fields to theHive but I am still getting a lot of extra junk imported into theHive.

So here is an example of my search string:

> index="index" host="host" malware-callback earliest=-6m latest=-1m | fields field1 field2 field3 field4 field5 field6 field7 field8

Results are:

> date host alert:  rawlogdata extrafield1=string extrafield2=num extrafield3=string field5=num extrafield4=num extrafield5=string extrafield6=string extrafield7=num extrafield8=string field3=string extrafield9=date field7=string field1=num extrafield10=num extrafield11=num extrafield12=string extrafield13=string field4=string extrafield14=string field8=num extrafield15=num extrafield16=string extrafield17=string extrafield18=string extrafield19=string field6=string extrafield20=string

Imports into theHive with the following observables:

> other | 1602872417 _no idea what this is, doesn't appear in alert_
> other | string _sourcetype field not included in query or results_
> other | index _index that was searched_ 
> other | string _splunk server, not in query or results_
> other | date _date and time_
> other | string _raw data appears to be part of imported log that is appearing at the front regardless of search structure_
> other | date _appears to be parsed from above string_
> other | 1602872418 | date _first extracted field plus the date_
> other | num _another segment of the raw data appearing at the front of the search results_
> other | string _another segment of the raw data appearing at the front of the search results_
> field8 | num
> field7 | string
> field6 | string
> field5 | num
> field4 | string
> field3 | string
> field2 | num
> field1 | num

**Comment by iamgrimm** [comment]
> I have tried to minimize the fields but it isn't working. Is there a way you can think of that would eliminate all the extra "other" fields? I thought this query would send only the requested fields to theHive but I am still getting a lot of extra junk imported into theHive.
> 
> So here is an example of my search string:
> 
> > index="index" host="host" malware-callback earliest=-6m latest=-1m | fields field1 field2 field3 field4 field5 field6 field7 field8
> 
> Results are:
> 
> > date host alert:  rawlogdata extrafield1=string extrafield2=num extrafield3=string field5=num extrafield4=num extrafield5=string extrafield6=string extrafield7=num extrafield8=string field3=string extrafield9=date field7=string field1=num extrafield10=num extrafield11=num extrafield12=string extrafield13=string field4=string extrafield14=string field8=num extrafield15=num extrafield16=string extrafield17=string extrafield18=string extrafield19=string field6=string extrafield20=string
> 
> Imports into theHive with the following observables:
> 
> > other | 1602872417 _no idea what this is, doesn't appear in alert_
> > other | string _sourcetype field not included in query or results_
> > other | index _index that was searched_
> > other | string _splunk server, not in query or results_
> > other | date _date and time_
> > other | string _raw data appears to be part of imported log that is appearing at the front regardless of search structure_
> > other | date _appears to be parsed from above string_
> > other | 1602872418 | date _first extracted field plus the date_
> > other | num _another segment of the raw data appearing at the front of the search results_
> > other | string _another segment of the raw data appearing at the front of the search results_
> > field8 | num
> > field7 | string
> > field6 | string
> > field5 | num
> > field4 | string
> > field3 | string
> > field2 | num
> > field1 | num

For the record I discovered that if I append `| FIELDS - _*` to my query it removes all of the extra splunk junk leaving me with only the fields I need, Fields 1 - 8 so that was a Splunk search issue not an issue with the app.  This leaves only the issue where duplicate message names are created when alerts occur too close together causing some alerts to not be created.

**Comment by remg427** [comment]
Hi,
in alert action, there is a param th_onlyDT that allows you to all regular fields in the alert or just fields you have added to the lookup thehive_datatypes.csv as artifacts
fields _* are anyway cleanup by the script so no need to remove in the search 
in Splunk I usually use | table to prepare fields rather than fields

**Comment by iamgrimm** [comment]
Upgraded to version 1.1.3  Although everything looks nice with the new features, my alerts are being created but now they all come in as "other" observable type, despite previously coming in properly.  `|inputlookup thehive_datatypes.csv` shows that fields are properly mapped to data types as they were before..

**Comment by iamgrimm** [comment]
In addition to all fields importing to theHive as "other" I am also now getting an additional field with the message "rid" that is always a numerical value, most of the time 0 sometimes 1.

**Comment by remg427** [comment]
Could you test version 1.1.4 and select scope "Include only listed fields in thehive_datatypes.csv"

**Comment by iamgrimm** [comment]
I am waiting for approval to upgrade to 1.1.4, but in the meantime, when I changed 1.1.3  setting to "Include only listed fields in thehive_datatypes.csv" the alert stopped creating events in thehive altogether.  I clicked "open in search" in the app and there are 6 events for today that should have created alerts, but nothing.
