### ISSUE TITLE
Hive-CE 1.1.2 App certification for Splunk Cloud 

### ISSUE THREAD

**Issue by VVX7** [remg427/TA-thehive-ce#16]
Hi

Trying to get 1.1.2 certified for Splunk Cloud.  It was rejected for the following reason:

- Logging sensitive information like proxy credentials. This is not allowed in Splunk cloud. Remove this log. File: bin/hive_common.py Line Number: 331

Thanks

**Comment by remg427** [comment]
done on 1.1.3
