### ISSUE TITLE
TheHive4 compatible?

### ISSUE THREAD

**Issue by pcyr44** [remg427/TA-thehive-ce#19]
Has this app been tested on TheHive4 interface? This was working on TheHive3 version but now I am getting a 400 status code when attempting to create alerts on TheHive4 after upgrade. I am also able to view alerts which have been created in TheHive by other means within TheHive with the hivecollect function, just unable to create alerts using this app. Thanks for any input.

**Comment by pcyr44** [comment]
Disregard, Splunk application was showing 400, actual status code was 401.

**Comment by remg427** [comment]
Hello,
Short answer is yes tested on both. 3.4 and 4
-- 
Sent with K-9 Mail.
