### ISSUE TITLE
Purpose of rid -field?

### ISSUE THREAD

**Issue by mluhta** [remg427/TA-thehive-ce#20]
Hi,

Version 1.1.2 of TA-thehive-ce added a `rid` field to every alert and thus it breaks TheHive's case similarity matching function.
What is the purpose of the field, and could it be removed with a setting for example?

![image](https://user-images.githubusercontent.com/12100880/100075291-7297b500-2e48-11eb-9d7a-6b29af923713.png)

**Comment by remg427** [comment]
Hi
rid is an internal field. I will remove it in future version.
What values has this field?
Could you update to 1.1.4?
In that version alerts can take only field names listed in thehive_datatypes.csv so rid won't be pushed to thehive.


-- 
Sent with K-9 Mail.

**Comment by mluhta** [comment]
Hi,

Thank you for the response! The value of the field seems to always be 0.
I could update to 1.1.4, but our use case requires sending all of the fields found in the search results to TheHive.

**Comment by remg427** [comment]
Ok will remove it in code
-- 
Sent with K-9 Mail.

**Comment by runninbutt** [comment]
What is the status of this?
