### ISSUE TITLE
Unexpected error: 'TypeError' object has no attribute 'message'.

### ISSUE THREAD

**Issue by user794dy** [remg427/TA-thehive-ce#5]
When attempting to use the alert action from Splunk the The Hive it appears to fail with the following error:
![IMG_4707](https://user-images.githubusercontent.com/69671468/90232401-4e7a1000-de25-11ea-969a-d59c97354c93.JPEG)

Configuration of lookup tables:
thehive_datatypes.csv: default
thehive_instance_list.csv
![IMG_4708](https://user-images.githubusercontent.com/69671468/90232505-76697380-de25-11ea-8a82-61bada4b7186.JPEG)

Everything was done according to manual:
https://github.com/remg427/TA-thehive-ce/blob/master/docs/thehivealerts.md

Any idea what can be wrong?

**Comment by remg427** [comment]
Hello, looks like the connection is not successful 
could you check that URL is reachable from splunk server, that API key is the correct one on stored thehive_api_key1?

**Comment by user794dy** [comment]
Than you for answering!
I have checked the connection with Splunk server with the help of Postman (created curl -XPOST request) and found out that the problem is that I don`t have sourceRef field in payload.
![IMG_5643](https://user-images.githubusercontent.com/69671468/90393004-9bb1e800-e098-11ea-8cf2-c69145f0643c.JPEG)

If I send the request with this field in payload (add anything, simple string), the correct answer is returned.
![IMG_5645](https://user-images.githubusercontent.com/69671468/90394626-a91ca180-e09b-11ea-8966-ba935d20d042.JPEG)
?

I have found the piece of code which describes the field sourceRef (in modalert_thehive_ce_alert_helper.py )  but don`t know what to do with it. 
![image](https://user-images.githubusercontent.com/69671468/90394804-00227680-e09c-11ea-9ede-e5eb256bad4a.png)


Can you advise something for this case?





> Hello, looks like the connection is not successful
> could you check that URL is reachable from splunk server, that API key is the correct one on stored thehive_api_key1?

**Comment by remg427** [comment]
sourceRef must be a new value each time. no alert update for now
