### ISSUE TITLE
Process for sending an alert that takes too long.

### ISSUE THREAD

**Issue by mlp1515** [remg427/TA-thehive-ce#6]
Hi,

when I use the TA_thehive_ce application to send a splunk alert to thehive it takes 7 seconds to be sent. 
I sometimes have up to 100 alerts for a splunk request and therefore more than 10 minutes to get all the alerts in thehive.
I found 3 requests for 3 web requests that take 2 seconds each to get configuration elements.

![001](https://user-images.githubusercontent.com/69857628/90526214-a2576280-e15f-11ea-8a51-82181e99cef0.PNG)

![002](https://user-images.githubusercontent.com/69857628/90526810-5ce76500-e160-11ea-81e6-d5cef6fe6d91.PNG)

Do you have an idea how to solve this problem? 
Thanks in advance #

**Comment by remg427** [comment]
Hello, could you check with latest version if this is better

**Comment by mlp1515** [comment]
Hello, yes version 1.1.0 fixes my problem.
Thank you for your reactivity.
